### PR TITLE
Conformance test fixes

### LINKED ISSUE #290: Light client conformance tests differences between description and real errors
When running tests for light client I noticed that for `not_enough_commits` (in the current canonical implementation) and `invalid_validator_set` (the new one in `light-client`) the expected error based on the description is not the same as the error we get when the test is run.

`not_enough_commits`: fails with `InvalidNextValidatorSet` for height 5 instead of `InsufficientCommitPower` for height 6

`invalid_validator_set`: fails with `request for height 6` instead of invalid `InvalidNextValidatorSet` for height 11

### PR DESCRIPTION
**Pull request by Shivani912**
closes #290 
partially addresses: #320 (bisection)

**UPDATE**: moved `single_peer/invalid_validator_set` to `multi_peer/malicious_validator_set` because it seemed more appropriate. 

**QUESTION**: Why do we don't run the `multi_peer/...` tests yet? 

* [X] Referenced an issue explaining the need for the change
* [ ] Updated all relevant documentation in docs
* [ ] Updated all code comments where relevant
* [ ] Wrote tests
* [ ] Updated CHANGES.md

### CODE REVIEW

File: light-client/tests/light_client.rs [hunk 1]
```diff
@@ -254,23 +254,12 @@ fn run_bisection_test(tc: TestBisection<LightBlock>) {
...
     for file_path in paths {
         let dir_entry = file_path.unwrap();
         let fp_str = format!("{}", dir_entry.path().display());
 
-        if skipped
-            .iter()
-            .any(|failing_case| fp_str.ends_with(failing_case))
-        {
-            println!("Skipping JSON test: {}", fp_str);
-            return;
```
Comment (liamsi) [inline light-client/tests/light_client.rs:271]: ouch, this should have been `continue` instead of `return`

File: light-client/tests/light_client.rs [hunk 2]
```diff
@@ -319,9 +308,9 @@ fn bisection() {
 #[test]
 fn single_step_sequential() {
     let dirs = [
-        "single_step/sequential/commit",
+        // "single_step/sequential/commit",
         "single_step/sequential/header",
-        "single_step/sequential/validator_set",
+        // "single_step/sequential/validator_set",
```
Comment (liamsi) [inline light-client/tests/light_client.rs:313]: Why are these dirs now commented out?

Comment (Shivani912) [reply light-client/tests/light_client.rs:313]: Oops, my bad!

**Comment by liamsi** [comment]
> QUESTION: Why do we don't run the multi_peer/... tests yet?

I think when you had them ready, we added them to this repo without the rust code being ready? 
https://github.com/informalsystems/tendermint-rs/blob/27298f0e7a5089096893f097d910f3e9271bf850/tendermint/tests/lite.rs#L193-L196

File: light-client/tests/light_client.rs (hunk 2 above)
Comment (liamsi) [reply light-client/tests/light_client.rs]: All good, thanks!

File: light-client/tests/light_client.rs (hunk 1 above)
Comment (liamsi) [reply light-client/tests/light_client.rs:271]: I think I introduced this and it was copied over and while it was fixed in the `lite` module, I didn't noticed the same here.

https://github.com/informalsystems/tendermint-rs/blob/27298f0e7a5089096893f097d910f3e9271bf850/tendermint/tests/lite.rs#L251-L256

**Comment by Shivani912** [comment]
> > QUESTION: Why do we don't run the multi_peer/... tests yet?
> 
> I think when you had them ready, we added them to this repo without the rust code being ready?
> 
> https://github.com/informalsystems/tendermint-rs/blob/27298f0e7a5089096893f097d910f3e9271bf850/tendermint/tests/lite.rs#L193-L196

Possible, `multi_peer` tests fail at the moment in rust code. Seems to me it's not fetching headers from a witness. Will have to take a closer look though!

**Comment by Shivani912** [comment]
Thanks @liamsi ! Will do that :)
