### PR TITLE
docs: Fix unclosed HTML tags errors

### LINKED ISSUE #1211: docs: Build fails
For the current docs on `main`, the documentation build fails, as per https://github.com/informalsystems/tendermint-rs/actions/runs/3236423129/jobs/5302211119 (ref: #1209).

Seems to be due to new checks in nightly.

### PR DESCRIPTION
**Pull request by thanethomson**
Closes #1211 

* [x] Referenced an issue explaining the need for the change
* [x] Updated all relevant documentation in docs
* [x] Updated all code comments where relevant
* [ ] Wrote tests
* [ ] Added entry in `.changelog/`

### CODE REVIEW

File: proto/src/serializers/bytes.rs [hunk 1]
```diff
@@ -18,7 +18,7 @@ pub mod hexstring {
             .map_err(serde::de::Error::custom)
     }
 
-    /// Serialize from T into hexstring
+    /// Serialize from `T` into hexstring
```
Comment (mzabaluev) [inline proto/src/serializers/bytes.rs:21]: I'd just say "a byte slice", it's generic.

File: proto/src/serializers/bytes.rs [hunk 2]
```diff
@@ -68,14 +68,14 @@ pub mod base64string {
     }
 }
 
-/// Serialize into Vec<base64string>, deserialize from Vec<base64string>
+/// Serialize into `Vec<base64string>`, deserialize from `Vec<base64string>`
```
Comment (mzabaluev) [inline proto/src/serializers/bytes.rs:71]: To avoid pseudo type references and generalize over serde formats:

```suggestion
/// Serialize into and deserialize from a sequence of _base64string_.
```

**Review by mzabaluev — APPROVED** [review]
Good fix, I only have a few stylistic suggestions to improve these docs while you are at it.
